Blog app: add devise
RitaDee/my-data-blog pull request #11
Opened 2023-05-25 07:58 UTC by RitaDee

### In this PR, we implemented the following 👎🏼 

- Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.

2023-05-25 08:16 UTC, brytebee approved these changes
Hi Team 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/ygx6guQZ3kxF8A80bC/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 08:30 UTC, RitaDee commented
Hello @brytebee,

Thank you for the review.

Please kindly state the changes required of me.

2023-05-25 09:34 UTC, brytebee requested changes

2023-05-25 09:34 UTC, brytebee commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
You should also add and implement the functionality of confirming the email of the users of your app.

<img width="1091" alt="image" src="https://github.com/RitaDee/my-data-blog/assets/27709832/fc0bbc60-2fb7-460f-9ff9-44c9995b3b36">

2023-05-25 09:35 UTC, brytebee commented
@RitaDee and @Divinity-dev and @HanaSabih I think it was a mixup with the network and it was pending on my PC but it is foxed now and you guys can make the updates.

2023-05-25 09:39 UTC, RitaDee commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
Noted with so many thanks @brytebee

2023-05-25 10:59 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi team 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 07:06 UTC, RitaDee commented
Thank you for the review @codepantha

2023-05-26 07:06 UTC, merged